### ISSUE TITLE
The link for the full dataset is 404.

### ISSUE THREAD

**Issue by KID-22** [rk2900/drsa#10]
The link(https://goo.gl/nUFND4) for the full dataset is 404. Could you please upload it again? Thank you very much.

**Comment by rk2900** [comment]
The dataset link still works. Please have a try again. Thanks.

**Comment by KID-22** [comment]
![image](https://user-images.githubusercontent.com/53068500/143241749-7ab712da-bcaa-488f-bb37-23c29c6f7d67.png)
Sorry, I still can't open it. Is my opening method wrong?
