### ISSUE TITLE
How to make correspondence between .log.txt in the CLINIC dataset and the csv file in the SUPPORT dataset?

### ISSUE THREAD

**Issue by ZiqianXie** [rk2900/drsa#2]
I couldn't make correspondence between the entries in train.log.txt with the entries in support2.csv. For example, the `race` column contains 16 distinct values in train.log.txt, however it only has 6 distinctive values in support2.csv. The same issue goes for other variables as well.

**Comment by rk2900** [comment]
We filtered out all the censored samples in the raw support2.csv since the data have no true event time of these samples.
We need to evaluate ANLP over the test data and it requires the true event time of samples. (While C-index does not need that.)
To simulate the censorship situation for the retained data, we conducted an observation experiments (sampling t from a uniform distribution). 

We will later experiment over the whole data on support2.csv. However, the performance will only be reported on C-index metric.

**Comment by ZiqianXie** [comment]
Thanks for your answer, but I want to know how the values are calculated in the columns of .log.txt. The `race` column has 16 distinct values, the `sodium` column has 500 distinct values while the corresponding columns in the support2.csv only have 6 and 61 distinct values respectively.

**Comment by rk2900** [comment]
> Thanks for your answer, but I want to know how the values are calculated in the columns of .log.txt. The `race` column has 16 distinct values, the `sodium` column has 500 distinct values while the corresponding columns in the support2.csv only have 6 and 61 distinct values respectively.

It seems that we have used a larger dataset with the same schema of support2.csv.
We will figure out and put the link of the original data in the readme.

**Comment by leilin-research** [comment]
We have a clinical dataset and would like to try the model. However, we cannot figure out the correspondence between the raw support2.csv and the .log.txt file either.

**Comment by abhishekmishra2505** [comment]
Can you please share the steps of pre-processing used to transform .log.txt file into .yzbx.txt ?
I am looking for logic to create featureindex.txt and .yzbt.txt .

**Comment by qinjr** [comment]
We have uploaded the feature engineering code for the CLINIC dataset(support dataset). And the raw data files are uploaded too. You can find the feature engineering code in the `python` directory, and the raw data in `data/support/raw/`.
For BIDDING dataset, we use the iPinYou dataset, you can find it [here](https://github.com/wnzhang/make-ipinyou-data/tree/master/python). Feature engineering part is the `mkyzx.py`.

**Comment by abhishekmishra2505** [comment]
Thanks for sharing feature engineering code.
I tried to execute DRSA.py but got below error :
**TypeError: Value passed to parameter 'multiples' has DataType float32 not in list of allowed values: int32, int64**

File :  "\drsa\python\BASE_MODEL.py", line 258, in add_time
    y = tf.reshape(tf.tile(x, [self.MAX_SEQ_LEN]), [self.MAX_SEQ_LEN, self.MIDDLE_FEATURE_SIZE])

**Comment by LLLLucensus** [comment]
> Thanks for sharing feature engineering code.
> I tried to execute DRSA.py but got below error :
> **TypeError: Value passed to parameter 'multiples' has DataType float32 not in list of allowed values: int32, int64**
> 
> File : "\drsa\python\BASE_MODEL.py", line 258, in add_time
> y = tf.reshape(tf.tile(x, [self.MAX_SEQ_LEN]), [self.MAX_SEQ_LEN, self.MIDDLE_FEATURE_SIZE])

I also got this error. Have you solve the problem?

**Comment by AliMoallemi** [comment]
> > Thanks for sharing feature engineering code.
> > I tried to execute DRSA.py but got below error :
> > **TypeError: Value passed to parameter 'multiples' has DataType float32 not in list of allowed values: int32, int64**
> > File : "\drsa\python\BASE_MODEL.py", line 258, in add_time
> > y = tf.reshape(tf.tile(x, [self.MAX_SEQ_LEN]), [self.MAX_SEQ_LEN, self.MIDDLE_FEATURE_SIZE])
> 
> I also got this error. Have you solve the problem?

In BASE_MODEL
line 173 change
self.MAX_SEQ_LEN = MAX_SEQ_LEN / self.DISCOUNT + 10
to
self.MAX_SEQ_LEN = int(MAX_SEQ_LEN / self.DISCOUNT + 10)
