### ISSUE TITLE
test_result calculation

### ISSUE THREAD

**Issue by SZH1230456** [rk2900/drsa#7]
I wonder how to calculate the patient status in the test set. From my point of view, the time information could not be sent into the model, because it involves the patient status directly.  We are supposed to multiply the results from RNN from the initial time to horizon time and use it as the survival status. However, I found that you just fed the time information into the model, like :
![image](https://user-images.githubusercontent.com/38172534/102344457-e441c980-3fd6-11eb-8bdc-8447d210802f.png)
Could you please explain it? Thank you!

**Comment by rk2900** [comment]
Hi, you can feed into the model with any time information, and the model will estimates the survival **probability** (not status) at the given time.
