### ISSUE TITLE
FIND_PARAMETERS

### ISSUE THREAD

**Issue by cwzhou** [rk2900/drsa#8]
Hello,

I was wondering how you tuned your hyperparameters for DRSA. I saw that in BASE_MODEL.py, there was a "FIND_PARAMETERS" argument but no corresponding definition or function for that. I didn't see in your paper a section regarding how you chose the hyperparameters that you did.

Thank you for your time!

**Comment by rk2900** [comment]
We use grid search over the learning rates and regularization parameters for all the compared methods.

**Comment by cwzhou** [comment]
Would you be able to share your scripts for the hyperparameter tuning?
