### ISSUE TITLE
how to find predicted risk scores or predictions?

### ISSUE THREAD

**Issue by cwzhou** [rk2900/drsa#9]
Hello, I want to calculate the concordance index on my own. How do I obtain the predicted risk for the different models using your code? I looked through your code but can't figure this out. DRSA, DeepHit, etc. Thanks!

**Comment by rk2900** [comment]
you can calculate the risk as (1-S) and the S has been obtained through the multiplication of (1-h) as that in our paper.

**Comment by cwzhou** [comment]
So as a follow-up, does this mean the current code doesn't store model predictions for each individual for clinical use?

**Comment by rk2900** [comment]
We did not save the model outputs. But it's quite easy to get the corresponding outputs for each sample and serialize them onto the memory or the disk.
